// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import (
	model "covid-summary/business/model"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetCovidSummary provides a mock function with given fields:
func (_m *Service) GetCovidSummary() (model.ResponseCovidSummary, error) {
	ret := _m.Called()

	var r0 model.ResponseCovidSummary
	if rf, ok := ret.Get(0).(func() model.ResponseCovidSummary); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.ResponseCovidSummary)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
